### ISSUE TITLE
PG::UndefinedFunction: ERROR:  function uuid_generate_v4() does not exist

### ISSUE THREAD

**Issue by schneems** [interagent/pliny#63]
When running db:migrate I get this error

```
PG::UndefinedFunction: ERROR:  function uuid_generate_v4() does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

Maybe this should be added to the first migration? 

```ruby
    self.execute <<-EOF
      CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    EOF
```

**Comment by dmcinnes** [comment]
I believe this should be fixed with the latest release

**Comment by kennyp** [comment]
:+1: I think we're good on this one now.

**Comment by johnbeynon** [comment]
I've just tried this with a new 0.7.3 app and it still doesn't deploy to Heroku cleanly - https://gist.github.com/johnbeynon/b687826ab82752bea863

**Comment by brandur** [comment]
@johnbeynon Ugh, I think we need to clarify the docs, but `bin/setup` is more suitable for local development than for platform deployment. One of the things it does is try to bring up a Postgres database for you by attaching to your locally running Postgres daemon (obviously impossible on a dyno).

Try this instead:

```
bundle exec rake schema:load migrate seed
```

**Comment by johnbeynon** [comment]
Yeah, that definitely works. I made the mistake of migrating first but then the uuid function didn't exist for the primary keys.






On Sat, Mar 21, 2015 at 10:53 AM -0700, "Brandur" <notifications@github.com> wrote:












@johnbeynon Ugh, I think we need to clarify the docs, but bin/setup is more suitable for local development than for platform deployment. One of the things it does is try to bring up a Postgres database for you by attaching to your locally running Postgres daemon (obviously impossible on a dyno).



Try this instead:

bundle exec rake schema:load migrate seed

**Comment by pedro** [comment]
`bin/setup` should now work in prod (see #184)
thanks folks!
